---
language: python
python: "2.7"
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-lxc/stable'
    packages:
    - python-pip
    - lxc

env:
  - LXC_NAME=jessie-test LXC_ROOTFS=/var/lib/lxc/$LXC_NAME/rootfs

install:
  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\nhost_key_checking=False' >ansible.cfg

script:
  # Create and configure LXC container to test against
  - sudo MIRROR=http://mirrors.us.kernel.org/debian lxc-create -n $LXC_NAME -t debian
  - sudo lxc-start -n $LXC_NAME && sleep 5
  - sudo lxc-attach -n $LXC_NAME -- apt-get -y --force-yes install python
  - sudo lxc-attach -n $LXC_NAME -- mknod -m 666 /dev/fuse c 10 229
  - sudo /bin/bash -c "printf '\n$(sudo lxc-info -Hin $LXC_NAME) test.lxc' >> /etc/hosts"
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
  - sudo mkdir -vm 0700 $LXC_ROOTFS/root/.ssh/
  - sudo cp -v ~/.ssh/id_rsa.pub $LXC_ROOTFS/root/.ssh/authorized_keys

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Perform a test run with the playbook
  - ansible-playbook tests/test.yml -i tests/inventory

  # Perform a another test run with the playbook to check for idempotency
  - >
    ansible-playbook tests/test.yml -i tests/inventory
    | grep -qP 'changed=0.*failed=0'
    && (echo "Idempotence: PASS"; exit 0)
    || (echo "Idempotence: FAIL"; exit 1)

  # Test Proxmox Web UI is online
  - curl -k https://test.lxc:8006

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: UJQvEXSj1m0U/fExnUiThV7TBX8fysJZ8X1QOq2HzEJO35SvK5V/2lgTy/QNqKcAoWPPuh9+81CzRV27cyO8W4sY+Op0Ld29rmoDy3A2yo9UHk7B4H7Q7y2ELGNvIiQZ47gXSWeeRdDE4hHxaE/MHpLItUhw6omSmOf1X+nF/6PAZECQuIcaBGjdI0NMIqF/+SULJ8U/RVKP9jLYOUNM0qP9wgmXaCxw8iCwZlsnYWeXVCSS7pCUG7PTMuOior7VPQL78yG+s4M6fdX8cmrRrl2p2TTqJM+u5yHtDyRKZ01wuD8gTmoMzDlPgaobNb3JBbYAwGVmN9h80iuPqAovh3hxXgkMnNWUEamq6+AppM73y/kzOKSS4+1SIgKOkIQvqSW1BsgUH8XbQXgaylz2pMpnooPk5L/Hp2GF832yBz3xF/oCo3R/ySY3EfZLMte7pDvrBOZFDbCtluxGWNOHzBMXKUW+MjJEtpz9GEvcvhVxJyVD4hOFdrVPCODlScAKNCF2oO917oRj0H2g9Bups6SMYMHwBMt6gVb1L/1NJP4f3r5FjzfVL1g1LmRMd3PvUIBihyDUnPpksBazCgNKZi+6dJd8yFBowi983VthSLAzysmzAAFK9GzqIT3Yv1QURvc1JHH/PSEo36vNzNVFEaVSu9VojPzplMExs+XJuwQ=
