---
language: python
python: "2.7"
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-lxc/stable'
    packages:
    - python-pip
    - lxc

cache:
  directories:
    - $HOME/lxc/
  pip: true

before_cache:
  - mkdir $HOME/lxc
  - sudo tar cf $HOME/lxc/cache.tar /var/cache/lxc/
  - sudo chown $USER. $HOME/lxc/cache.tar

env:
  - LXC_NAME=jessie-test LXC_ROOTFS=/var/lib/lxc/$LXC_NAME/rootfs

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\nhost_key_checking=False' >ansible.cfg

before_script:
  - sudo tar xf $HOME/lxc/cache.tar -C / || echo "Didn't extract cache."

script:
  # Create and configure LXC container to test against
  - sudo MIRROR=http://mirrors.us.kernel.org/debian lxc-create -n $LXC_NAME -t debian
  - sudo lxc-start -n $LXC_NAME && sleep 5
  - sudo lxc-attach -n $LXC_NAME -- apt-get -y --force-yes install python
  - sudo lxc-attach -n $LXC_NAME -- mknod -m 666 /dev/fuse c 10 229
  - sudo /bin/bash -c "printf '\n$(sudo lxc-info -Hin $LXC_NAME) test.lxc' >> /etc/hosts"
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
  - sudo mkdir -vm 0700 $LXC_ROOTFS/root/.ssh/
  - sudo cp -v ~/.ssh/id_rsa.pub $LXC_ROOTFS/root/.ssh/authorized_keys

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Perform a test run with the playbook
  - ansible-playbook tests/test.yml -i tests/inventory --skip skiponlxc

  # Perform a another test run with the playbook to check for idempotency
  - >
    ansible-playbook tests/test.yml -i tests/inventory --skip skiponlxc
    | grep -qP 'changed=0.*failed=0'
    && (echo "Idempotence: PASS"; exit 0)
    || (echo "Idempotence: FAIL"; exit 1)

  # Test Proxmox Web UI is online
  - curl -k https://test.lxc:8006

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: ftqNxPWTKL0GTozlHohkYIoh+8j/bQe7lLt+5gtzvvdFhF9N/99KCRgMRVVp9ggNyPp3fELpKXtdeLv4/RXDYtlNWR/dRR5l1vgUoXA/kA6UBJ52LziivH8P84Pe6G9Iy20SHC9nhm16yHmiivXxdS41pi5Mbs+Mblog9jYLBKXY0V9nlrv/agfdLmR3qk5mxAtPNPHYfC+R3YjedPasK7nyEYaWV29uHH3rEjhnrjRwdNuB981K7T+l5vIKieXNvsF+kaXYWGKxY57J/zFuZfyLXXFVE8XMwIA1spWG/FVcq6TQGAkB+n1NcHPSeeeb5Rt6IrUP7LTAjCGMcM2hQqTbq0Xce00FGd4qEWqpw0AtX//vBlynGnCjlS0FstRri+ZlsAn7micr/DcnGJYFNhvn6c8p4TDIgCnp4uifYyZJyxx4aOXwscs77N4VKYnfy53Um8TJOt8yQe2dHRpNV2QZWnODhtH9NSQt7AI0SkitCFVjr4iDeoQ/bds6agxpfAtoNNjaRV1MSxSi7ruBQHDQbzT9qRXak3BMp0BrkHM9XOXdVDnmHtCvBIy7qW2qWqTwQ+Eg4so2qnMAK+o53Qhu6mWx6XRYW/MHLbs4ez5t4ABsVBg0ZQiiBA4Iq6c8666ORGOxk65+TNyyl3QlgLwwuASQig1HFFzioWGZvTc=

