---
name: Publish to Galaxy

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch: {}

jobs:
  build:
    name: Publish to Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: robertdebock/galaxy-action@7d89099e09f4385ec4b53eb58c0d120f1ad806dd # 1.2.1
        with:
          galaxy_api_key: ${{ secrets.MILKY_WAY }}
          git_branch: main
